image:
  name: hashicorp/terraform:latest

  entrypoint:
    - ""

stages:
  - format
  - validate
  - test
  - deploy
  - destroy

variables:
  TF_ROOT: "infra"
  PYTHONPATH: "$CI_PROJECT_DIR"

before_script:
  - apk add --no-cache python3 py3-pip zip bash
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

#################################################
# TERRAFORM FORMAT
#################################################

terraform_format:
  stage: format

  script:
    - cd $TF_ROOT
    - terraform fmt


#################################################
# TERRAFORM VALIDATE
#################################################

terraform_validate:
  stage: validate

  script:
    - ls -R src/
    - cd $TF_ROOT
    - terraform init
    - terraform validate

#################################################
# TESTS
#################################################

test:
  stage: test
  script:
    - source venv/bin/activate
    - python -m py_compile src/lambda_code/*.py
    - pytest tests/ -v

#################################################
# DEPLOY LAMBDA
#################################################

deploy_lambda:
  stage: deploy

  script:
    - cd $TF_ROOT
    - terraform init
    - terraform apply -auto-approve -target=aws_lambda_function.lambda_function

  when: manual


#################################################
# MANUAL DESTROY
#################################################

terraform_destroy:
  stage: destroy

  script:
    - cd $TF_ROOT
    - terraform init
    - terraform destroy -auto-approve

  when: manual