sonar.projectKey=sairam1619_deploy_lambda
sonar.organization=sairam1619

sonar.sources=src
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
